/*
Copyright (c) 2019-2020 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module forest;

import std.stdio;
import std.random;
import std.math;
import dagon;
import dagon.ext.nuklear;
import dagon.ext.ftfont;
import dagon.ext.physics;

//version = Winter;

void collectEntityTris(Entity e, ref DynamicArray!Triangle tris)
{
    if (e.solid && e.drawable)
    {
        e.updateTransformationDeep();
        Matrix4x4f normalMatrix = e.invAbsoluteTransformation.transposed;

        Mesh mesh = cast(Mesh)e.drawable;
        if (mesh is null)
        {
            Terrain t = cast(Terrain)e.drawable;
            if (t)
            {
                mesh = t.collisionMesh;
            }
        }

        if (mesh)
        {
            foreach(tri; mesh)
            {
                Vector3f v1 = tri.v[0];
                Vector3f v2 = tri.v[1];
                Vector3f v3 = tri.v[2];
                Vector3f n = tri.normal;

                v1 = v1 * e.absoluteTransformation;
                v2 = v2 * e.absoluteTransformation;
                v3 = v3 * e.absoluteTransformation;
                
                Vector3f nWorld = n * normalMatrix;

                Triangle tri2 = tri;
                tri2.v[0] = v1;
                tri2.v[1] = v2;
                tri2.v[2] = v3;
                tri2.normal = nWorld;
                tri2.barycenter = (tri2.v[0] + tri2.v[1] + tri2.v[2]) / 3;
                
                tris.append(tri2);
            }
        }
    }
}

BVHTree!Triangle entitiesToBVH(EntityGroup entityGroup)
{
    DynamicArray!Triangle tris;

    foreach(e; entityGroup)
        collectEntityTris(e, tris);

    if (tris.length)
    {
        BVHTree!Triangle bvh = New!(BVHTree!Triangle)(tris, 4);
        tris.free();
        return bvh;
    }
    else
        return null;
}

class ForestScene: Scene
{
    Game game;
    LoadingScreen loadingScreen;

    FontAsset aFont;

    OBJAsset aMeshGun;
    TextureAsset aTexGunAlbedo;
    TextureAsset aTexGunNormal;
    TextureAsset aTexGunRoughness;
    TextureAsset aTexGunMetallic;

    PackageAsset aScene;

    ImageAsset aHeightmap;

    TextureAsset aSplatmapPavement;
    TextureAsset aSplatmapGrass;

    TextureAsset aTexDesertAlbedo;
    TextureAsset aTexDesertNormal;
    TextureAsset aTexGrassAlbedo;
    TextureAsset aTexGrassNormal;
    TextureAsset aTexPavementAlbedo;
    TextureAsset aTexPavementNormal;
    
    TextureAsset aTexBoxDiffuse;
    TextureAsset aTexBoxNormal;

    TextureAsset aTexFireDiffuse;
    TextureAsset aTexSmokeDiffuse;

    TextureAsset aEnvmap;

    ImageAsset aTexSkyFront;
    ImageAsset aTexSkyBack;
    ImageAsset aTexSkyLeft;
    ImageAsset aTexSkyRight;
    ImageAsset aTexSkyTop;
    ImageAsset aTexSkyBottom;

    TextureAsset aTexDecalLeaves;
    
    TextureAsset aTexColorTable;

    OBJAsset aBushHi;
    OBJAsset aBushLow;
    TextureAsset aBush;
    
    OBJAsset aSpruce;
    TextureAsset aSpruceAlbedo;
    
    PhysicsWorld physicsWorld;
    BVHTree!Triangle bvh;

    Camera camera;
    FirstPersonViewComponent fpview;
    CharacterController character;

    Light sun;
    Entity eSky;
    RayleighShader rayleighShader;
    bool useSky = false;
    Cubemap envCubemap;

    ShapeSphere lightSphere;

    Entity eTerrain;

    FreeTypeFont font;
    Entity text;
    TextLine infoText;
    
    NuklearGUI gui;
    Entity eNuklear;

    float sunPitch = -20.0f;
    float sunTurn = 135.0f;

    this(Game game)
    {
        super(game);
        this.game = game;
        loadingScreen = New!LoadingScreen(game, this);
    }
    
    ~this()
    {
        if (bvh)
            bvh.free();
    }

    override void beforeLoad()
    {
        if (freetypeSupport != FTSupport.noLibrary && 
            freetypeSupport != FTSupport.badLibrary)
            aFont = this.addFontAsset("data/font/DroidSans.ttf", 14);

        aMeshGun = addOBJAsset("data/cerberus/cerberus.obj");
        aTexGunAlbedo = addTextureAsset("data/cerberus/cerberus-albedo.png");
        aTexGunNormal = addTextureAsset("data/cerberus/cerberus-normal.png");
        aTexGunRoughness = addTextureAsset("data/cerberus/cerberus-roughness.png");
        aTexGunMetallic = addTextureAsset("data/cerberus/cerberus-metallic.png");

        aScene = addPackageAsset("data/village/village.asset");

        version(Winter)
        {
            aHeightmap = addImageAsset("data/terrain/heightmap-snow.png");
            aSplatmapGrass = addTextureAsset("data/terrain/splatmap-snow.png");
            aTexPavementAlbedo = addTextureAsset("data/terrain/pavement-snow-albedo.png");
            aTexGrassAlbedo = addTextureAsset("data/terrain/grass-snow-albedo.png");
            aTexGrassNormal = addTextureAsset("data/terrain/grass-snow-normal.png");
            aBush = addTextureAsset("data/bush/bush-snow.png");
            aSpruceAlbedo = addTextureAsset("data/spruce/spruce-snow-diffuse.png");
        }
        else 
        {
            aHeightmap = addImageAsset("data/terrain/heightmap.png");
            aSplatmapGrass = addTextureAsset("data/terrain/splatmap-grass.png");
            aTexPavementAlbedo = addTextureAsset("data/terrain/pavement-albedo.png");
            aTexGrassAlbedo = addTextureAsset("data/terrain/grass-albedo.png");
            aTexGrassNormal = addTextureAsset("data/terrain/grass-normal.png");
            aBush = addTextureAsset("data/bush/bush.png");
            aSpruceAlbedo = addTextureAsset("data/spruce/spruce-diffuse.png");
        }
        aSplatmapPavement = addTextureAsset("data/terrain/splatmap-pavement.png");

        aTexDesertAlbedo = addTextureAsset("data/terrain/desert-albedo.png");
        aTexDesertNormal = addTextureAsset("data/terrain/desert-normal.png");

        aTexPavementNormal = addTextureAsset("data/terrain/pavement-normal.png");
        
        aTexBoxDiffuse = addTextureAsset("data/box/box-diffuse.png");
        aTexBoxNormal = addTextureAsset("data/box/box-normal.png");

        aTexFireDiffuse = addTextureAsset("data/particles/fire.png");
        aTexSmokeDiffuse = addTextureAsset("data/particles/smoke-diffuse.png");

        aEnvmap = addTextureAsset("data/TropicalRuins_Env.hdr");

        aTexSkyFront = addImageAsset("data/skybox/sky_front.png");
        aTexSkyBack = addImageAsset("data/skybox/sky_back.png");
        aTexSkyLeft = addImageAsset("data/skybox/sky_left.png");
        aTexSkyRight = addImageAsset("data/skybox/sky_right.png");
        aTexSkyTop = addImageAsset("data/skybox/sky_top.png");
        aTexSkyBottom = addImageAsset("data/skybox/sky_bottom.png");

        aBushHi = addOBJAsset("data/bush/bush-hi.obj");
        aBushLow = addOBJAsset("data/bush/bush-low.obj");
        
        aSpruce = addOBJAsset("data/spruce/spruce.obj");

        aTexDecalLeaves = addTextureAsset("data/decals/leaves1.png");
        
        aTexColorTable = addTextureAsset("data/filter1.png");
    }

    override void onLoad(Time t, float progress)
    {
        loadingScreen.update(t, progress);
        loadingScreen.render();
    }

    override void afterLoad()
    {
        physicsWorld = New!PhysicsWorld(assetManager);
        
        envCubemap = addCubemap(1024);
        //envCubemap.fromEquirectangularMap(aEnvmap.texture);
        envCubemap.setFaceImage(CubeFace.PositiveZ, aTexSkyFront.image);
        envCubemap.setFaceImage(CubeFace.NegativeZ, aTexSkyBack.image);
        envCubemap.setFaceImage(CubeFace.PositiveX, aTexSkyRight.image);
        envCubemap.setFaceImage(CubeFace.NegativeX, aTexSkyLeft.image);
        envCubemap.setFaceImage(CubeFace.PositiveY, aTexSkyTop.image);
        envCubemap.setFaceImage(CubeFace.NegativeY, aTexSkyBottom.image);
        environment.ambientMap = envCubemap;
        
        environment.backgroundColor = Color4f(0.8f, 0.8f, 1.0f, 1.0f);
        environment.ambientColor = environment.backgroundColor * 0.25f;

        camera = addCamera();
        fpview = New!FirstPersonViewComponent(eventManager, camera);
        //fpview.active = true;
        camera.position.y = 10.0f;
        game.renderer.activeCamera = camera;

        game.deferred.ssaoEnabled = true;
        game.deferred.ssaoPower = 3.0;
        game.postProc.motionBlurEnabled = true;
        game.postProc.motionBlurFramerate = 60;
        game.postProc.glowEnabled = true;
        game.postProc.glowThreshold = 1.0f;
        game.postProc.glowIntensity = 0.3f;
        game.postProc.glowRadius = 7;
        game.postProc.fxaaEnabled = true;
        game.postProc.lutEnabled = true;
        game.postProc.colorLookupTable = aTexColorTable.texture;
        game.postProc.lensDistortionEnabled = true;

        sun = addLight(LightType.Sun);
        sun.position.y = 50.0f;
        sun.shadowEnabled = true;
        version(Winter)
            sun.energy = 6.0f;
        else
            sun.energy = 10.0f;
        sun.scatteringEnabled = true;
        sun.scattering = 0.35f;
        sun.mediumDensity = 0.15f;
        sun.scatteringUseShadow = true;
        sun.color = Color4f(1.0f, 0.66f, 0.33f, 1.0f);

        lightSphere = New!ShapeSphere(1.0f, 24, 16, false, assetManager);

        eSky = addEntity();
        eSky.layer = EntityLayer.Background;
        auto psync = New!PositionSync(eventManager, eSky, camera);
        eSky.drawable = New!ShapeBox(Vector3f(1.0f, 1.0f, 1.0f), assetManager);
        eSky.scaling = Vector3f(100.0f, 100.0f, 100.0f);
        eSky.material = addMaterial();
        rayleighShader = New!RayleighShader(assetManager);
        eSky.material.depthWrite = false;
        eSky.material.culling = false;
        eSky.material.diffuse = envCubemap;
        
        version(Winter)
        {
        }
        else
        {
            auto eWater = addEntity();
            eWater.dynamic = false;
            eWater.castShadow = false;
            eWater.position = Vector3f(0, 4, 0);
            auto waterShader = New!WaterShader(game.deferredRenderer.gbuffer, assetManager, assetManager);
            waterShader.waterColor = Color4f(0.05f, 0.2f, 0.0f, 1.0f);
            eWater.material = addMaterial();
            eWater.material.blending = Transparent;
            eWater.material.shader = waterShader;
            eWater.material.sun = sun;
            eWater.drawable = New!ShapePlane(128, 128, 10, assetManager);
        }

        eTerrain = addEntity();
        eTerrain.dynamic = false;
        eTerrain.solid = true;
        eTerrain.position = Vector3f(-64, 0, -64);
        eTerrain.material = addMaterial();

        eTerrain.material.diffuse = aTexDesertAlbedo.texture;
        eTerrain.material.textureScale = Vector2f(50, 50);
        eTerrain.material.normal = aTexDesertNormal.texture;
        eTerrain.material.roughness = 0.8f;

        eTerrain.material.diffuse2 = aTexGrassAlbedo.texture;
        eTerrain.material.splatmap2 = aSplatmapGrass.texture;
        eTerrain.material.textureScale2 = Vector2f(50, 50);
        eTerrain.material.normal2 = aTexGrassNormal.texture;
        version(Winter) eTerrain.material.roughness2 = 0.6f;
        else eTerrain.material.roughness2 = 1.0f;

        eTerrain.material.diffuse3 = aTexPavementAlbedo.texture;
        eTerrain.material.splatmap3 = aSplatmapPavement.texture;
        eTerrain.material.textureScale3 = Vector2f(50, 50);
        eTerrain.material.normal3 = aTexPavementNormal.texture;
        version(Winter) eTerrain.material.roughness3 = 0.5f;
        else eTerrain.material.roughness3 = 0.7f;

        auto heightmap = New!ImageHeightmap(aHeightmap.image, 30.0f, assetManager);
        auto terrain = New!Terrain(512, 64, heightmap, assetManager);
        eTerrain.drawable = terrain;
        eTerrain.scaling = Vector3f(0.25f, 0.25f, 0.25f);

        aScene.entity.position.y = aScene.entity.position.y + 5.8f;
        useEntity(aScene.entity);
        foreach(name, entityAsset; aScene.entities)
        {
            auto entity = entityAsset.entity;
            entity.layer = EntityLayer.Spatial;
            entity.solid = true;
            useEntity(entity);
        }
        
        bvh = entitiesToBVH(spatial);
        if (bvh)
            physicsWorld.bvhRoot = bvh.root;
        
        auto eCharacter = addEntity();
        eCharacter.position = camera.position;
        auto characterSphere = New!GeomEllipsoid(physicsWorld, Vector3f(0.9f, 1.0f, 0.9f));
        character = New!CharacterController(eventManager, eCharacter, physicsWorld, 80.0f, characterSphere);
        character.rbody.layer = 1;
        auto characterSensorGeom = New!GeomBox(physicsWorld, Vector3f(0.5f, 0.5f, 0.5f));
        character.createSensor(characterSensorGeom, Vector3f(0.0f, -0.75f, 0.0f));
        
        auto rbBoxGeom = New!GeomBox(physicsWorld, Vector3f(0.5f, 0.5f, 0.5f));
        auto shBox = New!ShapeBox(Vector3f(1, 1, 1), assetManager);
        auto mBox = addMaterial();
        mBox.diffuse = aTexBoxDiffuse.texture;
        mBox.normal = aTexBoxNormal.texture;
        
        foreach(i; 0..10)
        {
            auto eBox = addEntity();
            eBox.drawable = shBox;
            eBox.material = mBox;
            eBox.position = Vector3f(i * 0.05f, 10.0f + 3.0f * cast(float)i, 5.0f);
            eBox.scaling = Vector3f(0.5f, 0.5f, 0.5f);
            auto rbBox = physicsWorld.addDynamicBody(Vector3f(0, 0, 0), 0.0f);
            RigidBodyComponent rbBoxComp = New!RigidBodyComponent(eventManager, eBox, rbBox);
            physicsWorld.addShapeComponent(rbBox, rbBoxGeom, Vector3f(0.0f, 0.0f, 0.0f), 20.0f);
        }

        auto mParticlesSmoke = addMaterial();
        mParticlesSmoke.diffuse = aTexSmokeDiffuse.texture;
        mParticlesSmoke.particleSphericalNormal = true;
        mParticlesSmoke.shadeless = true;
        mParticlesSmoke.blending = Transparent;
        mParticlesSmoke.depthWrite = false;
        mParticlesSmoke.energy = 1.0f;
        mParticlesSmoke.sun = sun;
        
        auto mParticlesFire = addMaterial();
        mParticlesFire.diffuse = aTexFireDiffuse.texture;
        mParticlesFire.particleSphericalNormal = true;
        mParticlesFire.shadeless = true;
        mParticlesFire.blending = Additive;
        mParticlesFire.depthWrite = false;
        mParticlesFire.energy = 1.0f;
        mParticlesFire.sun = sun;

        auto eParticleSystem = addEntity();
        auto particleSystem = New!ParticleSystem(eventManager, eParticleSystem);
        
        auto eParticlesFire = addEntity();
        auto emitterFire = New!Emitter(eParticlesFire, particleSystem, 50);
        emitterFire.material = mParticlesFire;
        emitterFire.startColor = Color4f(1, 1, 1, 1);
        emitterFire.endColor = Color4f(0.5, 0.5, 0.0, 0);
        emitterFire.initialDirectionRandomFactor = 0.2f;
        emitterFire.scaleStep = Vector2f(-1.0, 1.5);
        emitterFire.rotationStep = 0.0f;
        emitterFire.minInitialSpeed = 5.0f;
        emitterFire.maxInitialSpeed = 10.0f;
        emitterFire.minSize = 0.5f;
        emitterFire.maxSize = 2.0f;
        emitterFire.minLifetime = 0.2f;
        emitterFire.maxLifetime = 1.0f;
        eParticlesFire.position = Vector3f(4, 6, -4);
        eParticlesFire.visible = true;
        
        auto eParticlesSmoke = addEntity();
        auto emitterSmoke = New!Emitter(eParticlesSmoke, particleSystem, 50);
        emitterSmoke.material = mParticlesSmoke;
        emitterSmoke.startColor = Color4f(1.0, 1.0, 1.0, 0.2);
        emitterSmoke.endColor = Color4f(1.0, 1.0, 1.0, 0);
        emitterSmoke.initialDirectionRandomFactor = 0.2f;
        emitterSmoke.scaleStep = Vector2f(1.0f, 1.0f); //Vector2f(-1.0, 1.5);
        emitterSmoke.rotationStep = 0.0f;
        emitterSmoke.minInitialSpeed = 5.0f;
        emitterSmoke.maxInitialSpeed = 10.0f;
        emitterSmoke.minSize = 0.5f;
        emitterSmoke.maxSize = 2.0f;
        eParticlesSmoke.position = Vector3f(4, 7, -4);
        eParticlesSmoke.visible = true;
        
        auto light = addLight(LightType.AreaSphere);
        light.castShadow = false;
        light.position = Vector3f(4, 6.5f, -4);
        light.color = Color4f(1.0f, 0.5f, 0.0f, 1.0f);
        light.energy = 20.0f;
        light.radius = 0.4f;
        light.volumeRadius = 10.0f;

        auto eVortex = addEntity();
        eVortex.position = Vector3f(2, 4, 0);
        auto vortex = New!Vortex(eVortex, particleSystem, 1.0f, 1.0f);
        
        Vector3f center = Vector3f(0.0f, 0.0f, 0.0f);
        
        auto mBushHi = addMaterial();
        mBushHi.diffuse = aBush.texture;
        mBushHi.culling = false;
        mBushHi.roughness = 1;
        mBushHi.specularity = 0;
        mBushHi.sun = sun;
        /*
        auto mBushLow = addMaterial();
        mBushLow.diffuse = aBush.texture;
        mBushLow.culling = false;
        mBushLow.roughness = 1;
        mBushLow.specularity = 0;
        mBushLow.sphericalNormal = true;
        */
        
        //auto lod = New!LODDrawable(assetManager);
        //lod.addLevel(aBushHi.mesh, mBushHi, 0.0f, 50.0f, 0.0f);
        //lod.addLevel(aBushLow.mesh, mBushLow, 50.0f, 500.0f, 0.0f);

        foreach(i; 0..50)
        {
            auto eBush = addEntity();
            eBush.dynamic = false;
            eBush.drawable = aBushHi.mesh;
            eBush.material = mBushHi;
            float rnd = uniform(0.4f, 1.0f);
            Vector2f pos = randomUnitVector2!float() * 50.0f;
            eBush.position = lerp(center, Vector3f(pos.x, 0.0f, pos.y), rnd);
            eBush.position.y = terrain.getHeight(eTerrain, eBush.position);
            eBush.scale(uniform(1.5f, 3.0f));
            eBush.turn(uniform(0.0f, 360.0f));
        }
        
        auto mSpruce = addMaterial();
        mSpruce.diffuse = aSpruceAlbedo.texture;
        mSpruce.culling = false;
        mSpruce.roughness = 1;
        mSpruce.specularity = 0;
        
        foreach(i; 0..50)
        {
            auto eTree = addEntity();
            eTree.dynamic = false;
            eTree.drawable = aSpruce.mesh;
            eTree.material = mSpruce;
            float rnd = uniform(0.4f, 1.0f);
            Vector2f pos = randomUnitVector2!float() * 50.0f;
            eTree.position = lerp(center, Vector3f(pos.x, 0.0f, pos.y), rnd);
            eTree.position.y = terrain.getHeight(eTerrain, eTree.position);
            eTree.scale(uniform(3.0f, 15.0f));
            eTree.turn(uniform(0.0f, 360.0f));
        }

        version(Winter)
        {
        }
        else
        {
            auto leavesDecalMaterial = addMaterial();
            leavesDecalMaterial.diffuse = aTexDecalLeaves.texture;
            leavesDecalMaterial.blending = Transparent;
            leavesDecalMaterial.depthWrite = false;
            leavesDecalMaterial.culling = false;
            leavesDecalMaterial.outputColor = true;
            leavesDecalMaterial.outputNormal = false;
            leavesDecalMaterial.outputPBR = false;

            auto decal = addDecal();
            decal.position = Vector3f(20, 0, 0);
            decal.scale(2.0f);
            decal.position.y = terrain.getHeight(eTerrain, decal.position);
            decal.material = leavesDecalMaterial;
        }
        
        if (nuklearSupport != NuklearSupport.noLibrary && 
            nuklearSupport != NuklearSupport.badLibrary)
        {
            gui = New!NuklearGUI(eventManager, assetManager);
            gui.addFont(aFont, 18, gui.localeGlyphRanges);
            eNuklear = addEntityHUD();
            eNuklear.drawable = gui;
            eNuklear.visible = true;
        }

        if (aFont)
        {
            text = addEntityHUD();
            infoText = New!TextLine(aFont.font, "Hello, World!", assetManager);
            infoText.color = Color4f(1, 1, 1, 0.7f);
            text.drawable = infoText;
            text.position.x = 10;
            text.position.y = eventManager.windowHeight - 10;
        }
        
        eventManager.showCursor(false);
    }

    Light addLightBall(Vector3f pos, Color4f color, float energy, float areaRadius, float volumeRadius)
    {
        auto light = addLight(LightType.AreaSphere);
        light.castShadow = false;
        light.position = pos;
        light.color = color;
        light.energy = energy;
        light.radius = areaRadius;
        light.volumeRadius = volumeRadius;

        auto lightGeom = addEntity(light);
        lightGeom.drawable = lightSphere;
        lightGeom.scaling = Vector3f(areaRadius, areaRadius, areaRadius);
        lightGeom.material = addMaterial();
        lightGeom.material.diffuse = color;
        lightGeom.material.emission = color;
        lightGeom.material.energy = energy;

        return light;
    }
    
    void updateCharacter()
    {
        Vector3f forward = camera.transformation.forward;
        Vector3f right = camera.transformation.right;
        float speed = 3.0f;
        Vector3f dir = Vector3f(0, 0, 0);
        if (inputManager.getButton("forward")) dir += -forward;
        if (inputManager.getButton("back"))    dir += forward;
        if (inputManager.getButton("left"))    dir += -right;
        if (inputManager.getButton("right"))   dir += right;
        character.move(dir.normalized, speed);
        
        if (inputManager.getButtonDown("jump")) 
        {
            character.jump(0.5f);
        }
        
        character.logicalUpdate();
    }

    char[100] textBuffer;

    override void onUpdate(Time t)
    {
        if (text && infoText)
        {
            text.position.y = eventManager.windowHeight - 10;

            uint n = sprintf(textBuffer.ptr, "FPS: %u Vis. static: %u Vis. dynamic: %u", 
                game.cadencer.fps, 
                game.deferred.passStaticGeometry.renderedEntities,
                game.deferred.passDynamicGeometry.renderedEntities);
            string s = cast(string)textBuffer[0..n];
            infoText.setText(s);
        }
        
        if (gui && eNuklear.visible)
            updateGUI(t);
        
        if (fpview.active)
        {
            updateCharacter();
        }

        sun.rotation =
            rotationQuaternion!float(Axis.y, degtorad(sunTurn)) *
            rotationQuaternion!float(Axis.x, degtorad(sunPitch));

        rayleighShader.sunDirection = -sun.rotation.rotate(Vector3f(0.0f, 0.0f, 1.0f));
        if (useSky)
            eSky.material.shader = rayleighShader;
        else
            eSky.material.shader = null;
        
        physicsWorld.update(t.delta);
        camera.position = character.rbody.position;
    }

    override void onKeyDown(int key)
    {
        if (key == KEY_ESCAPE)
            application.exit();
        else if (key == KEY_RETURN)
            eNuklear.visible = !eNuklear.visible;
        else if (key == KEY_BACKSPACE)
            gui.inputKeyDown(NK_KEY_BACKSPACE);
        else if (key == KEY_DELETE)
            gui.inputKeyDown(NK_KEY_DEL);
        else if (key == KEY_C && eventManager.keyPressed[KEY_LCTRL])
            gui.inputKeyDown(NK_KEY_COPY);
        else if (key == KEY_V && eventManager.keyPressed[KEY_LCTRL])
            gui.inputKeyDown(NK_KEY_PASTE);
        else if (key == KEY_A && eventManager.keyPressed[KEY_LCTRL])
            gui.inputKeyDown(NK_KEY_TEXT_SELECT_ALL);
    }
    
    override void onKeyUp(int key)
    {
        if (gui && eNuklear.visible)
        {
            if (key == KEY_BACKSPACE)
                gui.inputKeyUp(NK_KEY_BACKSPACE);
        }
    }
    
    override void onMouseButtonDown(int button)
    {
        if (gui && eNuklear.visible)
        {
            gui.inputButtonDown(button);
        }
    }
    
    override void onMouseButtonUp(int button)
    {
        bool unfocused = true;
        if (gui && eNuklear.visible)
        {
            gui.inputButtonUp(button);
            unfocused = !gui.itemIsAnyActive();
        }
        
        if (unfocused)
        {
            fpview.active = !fpview.active;
            eventManager.showCursor(!fpview.active);
            fpview.prevMouseX = eventManager.mouseX;
            fpview.prevMouseY = eventManager.mouseY;
        }
    }

    override void onTextInput(dchar unicode)
    {
        if (gui && eNuklear.visible)
            gui.inputUnicode(unicode);
    }

    override void onMouseWheel(int x, int y)
    {
        if (gui && eNuklear.visible && !fpview.active)
            gui.inputScroll(x, y);
    }

    override void onDropFile(string filename)
    {
        writeln(filename);
        assetManager.reloadAsset(aEnvmap, filename);

        if (envCubemap)
            assetManager.deleteOwnedObject(envCubemap);

        envCubemap = New!Cubemap(1024, assetManager);
        envCubemap.fromEquirectangularMap(aEnvmap.texture);

        environment.ambientMap = envCubemap;
        eSky.material.diffuse = envCubemap;
    }
    
    void updateGUI(Time t)
    {
        gui.update(t);
        
        if (gui.begin("Menu", NKRect(0, 0, eventManager.windowWidth, 40), 0))
        {
            gui.menubarBegin();
            {
                gui.layoutRowStatic(30, 40, 5);

                if (gui.menuBeginLabel("File", NK_TEXT_LEFT, NKVec2(200, 200)))
                {
                    gui.layoutRowDynamic(25, 1);
                    if (gui.menuItemLabel("New", NK_TEXT_LEFT)) { }
                    if (gui.menuItemLabel("Open", NK_TEXT_LEFT)) { }
                    if (gui.menuItemLabel("Save", NK_TEXT_LEFT)) { }
                    if (gui.menuItemLabel("Exit", NK_TEXT_LEFT)) { application.exit(); }
                    gui.menuEnd();
                }

                if (gui.menuBeginLabel("Edit", NK_TEXT_LEFT, NKVec2(200, 200)))
                {
                    gui.layoutRowDynamic(25, 1);
                    if (gui.menuItemLabel("Copy", NK_TEXT_LEFT)) { }
                    if (gui.menuItemLabel("Paste", NK_TEXT_LEFT)) { }
                    gui.menuEnd();
                }

                if (gui.menuBeginLabel("Help", NK_TEXT_LEFT, NKVec2(200, 200)))
                {
                    gui.layoutRowDynamic(25, 1);
                    if (gui.menuItemLabel("About...", NK_TEXT_LEFT)) { }
                    gui.menuEnd();
                }
            }
            gui.menubarEnd();
        }
        gui.end();
    }
}
